version: "3"
services:
  api:
    environment:
      - CHOKIDAR_USEPOLLING=true
      - MONGO_URL=mongodb://root:example@mongo:27017
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    restart: always
    depends_on:
      - "mongo"
  web:
    #need this env variable for windows
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
  door:
    depends_on:
      - api
      - web
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./door
    ports:
      - "6020:80"
  mongo:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
